# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20160401_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_user_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
