# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_save_user_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotpassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reset_password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('new_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='news_posts',
            name='image',
            field=models.FileField(default='images/name.jpg', upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
